[package]
name = "matrix"
version = "0.1.0"
authors = ["s0lst1ce"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
rand = "0.8"

[dependencies]
num = "0.3.1"
thiserror = "1.0"